// <auto-generated />
using System;
using Acme.Center.Platform.Shared.Infrastructure.Persistence.EntityFrameworkCore.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Acme.Center.Platform.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Acme.Center.Platform.Iam.Domain.Model.Aggregates.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Acme.Center.Platform.Profiles.Domain.Model.Aggregates.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_profiles");

                    b.ToTable("profiles");
                });

            modelBuilder.Entity("Acme.Center.Platform.Publishing.Domain.Model.Aggregate.Tutorial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("varchar(240)")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_tutorials");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("i_x_tutorials_category_id");

                    b.ToTable("tutorials");
                });

            modelBuilder.Entity("Acme.Center.Platform.Publishing.Domain.Model.Entities.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<int?>("TutorialId")
                        .HasColumnType("int")
                        .HasColumnName("tutorial_id");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<string>("asset_type")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("varchar(34)")
                        .HasColumnName("asset_type");

                    b.HasKey("Id")
                        .HasName("p_k_assets");

                    b.HasIndex("TutorialId")
                        .HasDatabaseName("i_x_assets_tutorial_id");

                    b.ToTable("assets");

                    b.HasDiscriminator<string>("asset_type").HasValue("asset_base");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Acme.Center.Platform.Publishing.Domain.Model.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_categories");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("Acme.Center.Platform.Publishing.Domain.Model.Entities.ImageAsset", b =>
                {
                    b.HasBaseType("Acme.Center.Platform.Publishing.Domain.Model.Entities.Asset");

                    b.Property<string>("ImageUri")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("image_uri");

                    b.ToTable("assets");

                    b.HasDiscriminator().HasValue("asset_image");
                });

            modelBuilder.Entity("Acme.Center.Platform.Publishing.Domain.Model.Entities.ReadableContentAsset", b =>
                {
                    b.HasBaseType("Acme.Center.Platform.Publishing.Domain.Model.Entities.Asset");

                    b.Property<string>("ReadableContent")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("readable_content");

                    b.ToTable("assets");

                    b.HasDiscriminator().HasValue("asset_readable_content");
                });

            modelBuilder.Entity("Acme.Center.Platform.Publishing.Domain.Model.Entities.VideoAsset", b =>
                {
                    b.HasBaseType("Acme.Center.Platform.Publishing.Domain.Model.Entities.Asset");

                    b.Property<string>("VideoUri")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("video_uri");

                    b.ToTable("assets");

                    b.HasDiscriminator().HasValue("asset_video");
                });

            modelBuilder.Entity("Acme.Center.Platform.Profiles.Domain.Model.Aggregates.Profile", b =>
                {
                    b.OwnsOne("Acme.Center.Platform.Profiles.Domain.Model.ValueObjects.EmailAddress", "Email", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("email_address");

                            b1.HasKey("Id")
                                .HasName("p_k_profiles");

                            b1.ToTable("profiles");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_profiles_profiles_id");
                        });

                    b.OwnsOne("Acme.Center.Platform.Profiles.Domain.Model.ValueObjects.PersonName", "Name", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("last_name");

                            b1.HasKey("Id")
                                .HasName("p_k_profiles");

                            b1.ToTable("profiles");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_profiles_profiles_id");
                        });

                    b.OwnsOne("Acme.Center.Platform.Profiles.Domain.Model.ValueObjects.StreetAddress", "Address", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("address_city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("address_country");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("address_number");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("address_postal_code");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("address_street");

                            b1.HasKey("Id")
                                .HasName("p_k_profiles");

                            b1.ToTable("profiles");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_profiles_profiles_id");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Acme.Center.Platform.Publishing.Domain.Model.Aggregate.Tutorial", b =>
                {
                    b.HasOne("Acme.Center.Platform.Publishing.Domain.Model.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_tutorials__category_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Acme.Center.Platform.Publishing.Domain.Model.Entities.Asset", b =>
                {
                    b.HasOne("Acme.Center.Platform.Publishing.Domain.Model.Aggregate.Tutorial", null)
                        .WithMany("Assets")
                        .HasForeignKey("TutorialId")
                        .HasConstraintName("f_k_assets_tutorials_tutorial_id");

                    b.OwnsOne("Acme.Center.Platform.Publishing.Domain.Model.Entities.AcmeAssetIdentifier", "AssetIdentifier", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<Guid>("Identifier")
                                .HasColumnType("char(36)")
                                .HasColumnName("asset_identifier");

                            b1.HasKey("Id")
                                .HasName("p_k_assets");

                            b1.ToTable("assets");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_assets__asset_id");
                        });

                    b.Navigation("AssetIdentifier")
                        .IsRequired();
                });

            modelBuilder.Entity("Acme.Center.Platform.Publishing.Domain.Model.Aggregate.Tutorial", b =>
                {
                    b.Navigation("Assets");
                });
#pragma warning restore 612, 618
        }
    }
}